version: '3.8'

services:

  backend:
    image: openjdk:17
    container_name: spring-boot-app
    working_dir: /app
    volumes:
      - ./target:/app
    command: ["java", "-jar", "project-discovery-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projectdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
